# Generated by Django 2.2.7 on 2019-11-21 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='n/a', max_length=100)),
                ('nationality', models.CharField(default='n/a', max_length=100)),
                ('photo_url', models.CharField(default='n/a', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='n/a', max_length=255)),
                ('album', models.CharField(default='n/a', max_length=255)),
                ('photo_url', models.CharField(default='n/a', max_length=300)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='tunr_app.Artist')),
            ],
        ),
    ]
